let games = [
    {
        id: 1,
        Nama: "Red Dead Redemption",
        OS: "Windows 10 64-Bit",
        Processor: ["Intel® Core™ i5-4670",  "AMD FX-9590"],
        Memory: 8,
        Graphics: ["NVIDIA GeForce GTX 960","AMD Radeon R7 360"],
        Storage: 12,
        Harga: 729000,
    },
    {
        id: 2,
        Nama: "Red Dead Redemption 2",
        OS: "Windows 10 64-Bit",
        Processor: ["Intel® Core™ i5-2500K",  "AMD FX-6300"],
        Memory: 8,
        Graphics: ["NVIDIA GeForce GTX 770 2GB","AMD Radeon R9 280 3GB"],
        Storage: 150,
        Harga: 879000,
    },
    {
        id: 3,
        Nama: "Wuthering Waves",
        OS: "Windows 10 64-Bit",
        Processor: ["Intel Core i5 (9th Gen)",  "Ryzen 2700"],
        Memory: 16,
        Graphics: ["NVIDIA GeForce GTX 1060","AMD Radeon RX 570", "Intel ARC A380"],
        Storage: 60,
        Harga: 0,
    },
    {
        id: 4,
        Nama: "Dota 2",
        OS: "Windows 7",
        Processor: ["Dual core from Intel at 2.8GHz",  "Dual core from AMD at 2.8GHz"],
        Memory: 4,
        Graphics: ["NVIDIA GeForce 8600", "NVIDIA GeForce 9600", "AMD Radeon HD2600", "AMD Radeon HD3600"],
        Storage: 60,
        Harga: 0,
    },
    {
        id: 5,
        Nama: "Stardew Valley",
        OS: "Windows Vista",
        Processor: ["2 GHz"],
        Memory: 2,
        Graphics: ["256 mb video memory"],
        Storage: 0.5,
        Harga: 115999,
    },
    {
        id: 6,
        Nama: "Hollow Knigh: Silksong",
        OS: "Windows 10 version 21H1 (build 19043)",
        Processor: ["Intel Core i3-3240", "AMD FX-4300"],
        Memory: 4,
        Graphics: ["GeForce GTX 560 Ti (1GB)", "Radeon HD 7750 (1GB)"],
        Storage: 8,
        Harga: 165999,
    },
    {
        id: 7,
        Nama: "Monster Hunter Wilds",
        OS: "Windows®10 (64-bit Required)",
        Processor: ["Intel® Core™ i5-10400", "Intel® Core™ i3-12100", "AMD Ryzen™ 5 3600"],
        Memory: 16,
        Graphics: ["NVIDIA® GeForce® GTX 1660(VRAM 6GB)", "AMD Radeon™ RX 5500 XT(VRAM 8GB)"],
        Storage: 75,
        Harga: 869000,
    },
    {
        id: 8,
        Nama: "PEAK",
        OS: "Windows 10",
        Processor: ["Intel Core i5 @ 2.5 GHz"],
        Memory: 8,
        Graphics: ["GTX 1060", "RX 6600 XT"],
        Storage: 4,
        Harga: 69999,
    }
];

export default games ;